### ISSUE TITLE
Support delivery info

### ISSUE THREAD

**Issue by Oehmi** [commercetools/csv-parser-orders#17]
### Description
We would like to suport the update actions "add deliveries".
(see https://dev.commercetools.com/http-api-projects-orders.html#add-delivery)

Due to the complexity of the delivery object, we are not able to structure an easy-to-use csv format. We have suggested a new structure for this (see possible solution).

_GroupByDelivery, ItemID, quantity and parcel.id_ are mandatory fields.

### Current Behavior
Not supported currently

### Possible Solution
There could be a GroupByDeliveryID which is only there to separate the deliveries from each other. So all line items with the same GroupByDeliveryID belongs to the same Delivery.
Inside this, the parcelID is available to separate the parcels from each other.
Clarify: Dies the ID have to be unique over all parcels or just inside the delivery?

**Comment by junajan** [comment]
> Clarify: Dies the ID have to be unique over all parcels or just inside the delivery?
ParcelIDs have to be unique only in the delivery not across all rows

**Comment by junajan** [comment]
Hello @Oehmi .. just to be sure - that example:
```
GroupByDelivery, ItemID, quantity and parcel.id are mandatory fields.
```

Instead of `GroupByDelivery` there should be `GroupByDeliveryID` right?

**Comment by junajan** [comment]
I updated a proposed structure a little bit and drafted an example here:
https://docs.google.com/spreadsheets/d/1dZgdNyJxLTWuzNzj3E0JgljlecfS6M6d4QW3LrcgnPA/edit#gid=0

Please take a look and share your thoughts if you have anything to add
