### ISSUE TITLE
Wrong Data is exported by module

### ISSUE THREAD

**Issue by hisabimbola** [commercetools/csv-parser-orders#9]
### Description

The [order-update](https://github.com/commercetools/orders-update) module expects the data to have `fromState` and `toState` but the data exported from this module is not compatible with the format required by ordersUpdate.

### Expected Behavior

Should export data in format expected by orders-update module

Expected data:
```json
[{
	"orderNumber": "234",
	"lineItems": [{
		"state": [{
			"quantity": 10,
			"fromState": "processing",
			"toState": "shipped"
		}]
	}]
}]
```
### Current Behavior

Current export data looks like this
```json
[{
	"orderNumber": "234",
	"lineItems": [{
		"state": [{
			"quantity": 10,
			"state": {
				"id": "shipped"
			}
		}]
	}]
}]
```

**Comment by Siilwyn** [comment]
Yes. And the fromState, toState fields contain the state key value.
